---
functional:
  - Пользователь должен иметь возможность просматривать рейтинг.
  - Пользователь должен иметь возможность играть с ботом.
  - Пользователь должен иметь возможность приглашать в игру другого пользователя.

non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть удобным на мобильном устройстве.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей).
implicit:
  - Пользователи должны иметь возможность видеть код друг друга в игре в режиме реального времени.
  - Пользователь должен иметь возможность зарегистрироваться на сайте
