---
functional:
  - Должна быть реализована система рейтингов пользователей.
  - Пользователь должен иметь возможность играть с ботом.
  - Пользователь должен иметь возможность приглашать в игру другого пользователя по ссылке.
  - требование 2
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть удобным на мобильном устройстве.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей).
implicit:
  - Пользователи должны иметь возможность видеть код друг друга в игре в режиме реального времени.
  - Пользователь должен иметь возможность авторизоваться на сайте.
